---
- name: Add bazel repo
  apt_repository: 
      repo='deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
      state=present
      mode=644

- name: Add bazel repo key
  apt_key:
      url=https://bazel.build/bazel-release.pub.gpg
      state=present

- name: Update cache and install bazel
  apt:
      name={{item}}
      state=latest
      update_cache=yes
  with_items:
      - bazel

- name: Remove second bazel repo
  file:
       path=/etc/apt/sources.list.d/bazel.list
       state=absent
