---
#- name: Update the certs
#  shell: apt-get install --reinstall ca-certificates

- name: Add Oracle Java Installer repo
  apt_repository:
    repo='ppa:webupd8team/java'
    update_cache=yes
    state=present
    mode=644
  tags: java

- name: Accept the Java License
  debconf:
    name='oracle-java7-installer'
    question='shared/accepted-oracle-license-v1-1'
    vtype='select'
    value='true'
  tags: java

- apt: update_cache=yes
  tags: java

- name: Install Oracle Java
  apt: name=oracle-java8-installer
    state=present
  tags: java
