---
#- name: Install ntp.conf
#  copy: src={{ item }} dest=/etc/
#  with_first_found:
#    ntp.conf:  
#      - "{{ ansible_hostname }}.conf"
#      - ntp.conf
#    paths:
#      - system/ntp/
#  notify: ntpd
# Bizare usage, don't suggest trying to make this work

- name: Install ntp client conf
  copy: src=ntp/ntp.conf dest=/etc/ntp.conf mode=644
  notify: ntp
