---
- name: Add ceph repo key
  apt_key:
     url=https://download.ceph.com/keys/release.asc
     state=present

- name: Install dependencies
  apt:
     name=python-software-properties
     state=present

- name: Pull in ceph repo
  apt_repository:
     repo="deb http://download.ceph.com/debian-{{ceph_release}}/ {{ansible_distribution_release}} main"
     state=present
     update_cache=yes

- name: Install ceph
  apt:
     name=ceph
     state=present

- include: conf.yml
