---
- name: Ensure argo link
  alternatives: 
     link=/usr/local/bin/{{item.name}}
     name={{ item.name }}
     path={{ item.path }}
  with_items:
     - { name: 'argo', path: '/site/local/argo/argouml.sh' }
