---
- name: Ensure mit-scheme link
  alternatives:
     link=/usr/local/bin/{{item.name}}
     name={{ item.name }}
     path={{ item.path }}
  with_items:
     - { name: 'mit-scheme', path: '/site/local/mit-scheme-9.2/bin/mit-scheme' }
