---
- name: Install apt/sources.list
  template: 
        src=sources.list.j2
        dest=/etc/apt/sources.list
        owner=root
        group=root mode=644

- name: Make a machine fix it's own packages
  copy: 
       src=40-fix-missing
       dest=/etc/apt/apt.conf.d/40fixmissing
       mode=644
       owner=root
       group=root
